"use client";

import { useState } from "react";
import { Activity, CheckCircle2, Clock3, Film, RefreshCw, Sparkles, Trash2, UserRound, Video, XCircle, Zap } from "lucide-react";
import { GenerationJob, getJobs, saveJobs } from "@/lib/foundation";

const filters = ["All jobs", "Processing", "Queued", "Completed"];

export default function JobsPage() {
  const [jobs, setJobs] = useState<GenerationJob[]>(() => getJobs());
  const [filter, setFilter] = useState("All jobs");
  const [notice, setNotice] = useState("");
  const filtered = jobs.filter((job) => filter === "All jobs" || filter.toLowerCase().startsWith(job.status));
  const cancelJob = (id: string) => { const next = jobs.map((job) => job.id === id && (job.status === "queued" || job.status === "processing") ? { ...job, status: "cancelled" as const } : job); setJobs(next); saveJobs(next); setNotice("Job cancelled and reserved credits released."); };
  const iconFor = (type: GenerationJob["type"]) => type === "character" ? <UserRound size={16} /> : type === "ad" ? <Sparkles size={16} /> : type === "image" ? <Film size={16} /> : type === "audio" ? <Activity size={16} /> : <Video size={16} />;
  const labelFor = (status: GenerationJob["status"]) => ({ queued: "Queued", processing: "Processing", completed: "Completed", failed: "Failed", cancelled: "Cancelled" })[status];

  return <div className="h-full overflow-y-auto bg-background"><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-gold"><Activity size={14} /> Generation queue</p><h1 className="mt-2 font-heading text-3xl font-semibold text-foreground">Your jobs, in one place.</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">Every generation reserves credits before submission and reports progress here with a customer-safe status.</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-400/15 bg-emerald-400/10 px-3 py-2 text-[10px] text-emerald-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" /> Queue healthy</div></div>{notice && <div className="mt-6 flex items-center gap-2 rounded-lg border border-gold/20 bg-gold/10 px-3 py-2.5 text-xs text-gold"><CheckCircle2 size={14} /> {notice}</div>}
    <div className="mt-8 flex flex-wrap gap-2">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full border px-3 py-1.5 text-[10px] ${filter === item ? "border-gold/40 bg-gold/10 text-gold" : "border-border text-muted-foreground hover:text-foreground"}`}>{item}</button>)}<button onClick={() => setJobs(getJobs())} className="ml-auto flex items-center gap-1.5 rounded-md border border-border px-3 py-1.5 text-[10px] text-muted-foreground hover:bg-surface-hover hover:text-foreground"><RefreshCw size={12} /> Refresh</button></div>
    <div className="mt-4 overflow-hidden rounded-xl border border-border bg-card"><div className="hidden grid-cols-[1fr_150px_100px_100px_100px] gap-4 border-b border-border px-5 py-3 text-[9px] font-semibold uppercase tracking-[0.14em] text-muted-foreground md:grid"><span>Job</span><span>Model</span><span>Status</span><span>Credits</span><span>Created</span></div><div className="divide-y divide-border">{filtered.map((job) => <div key={job.id} className="px-5 py-4"><div className="grid gap-3 md:grid-cols-[1fr_150px_100px_100px_100px] md:items-center md:gap-4"><div className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-gold/10 text-gold">{iconFor(job.type)}</div><div className="min-w-0"><p className="truncate text-xs font-medium text-foreground">{job.label}</p><p className="mt-1 truncate text-[10px] text-muted-foreground">ID {job.id} · {job.type}</p></div></div><span className="text-[10px] text-muted-foreground">{job.model}</span><span className={`flex items-center gap-1.5 text-[10px] ${job.status === "completed" ? "text-emerald-300" : job.status === "failed" ? "text-red-300" : job.status === "cancelled" ? "text-muted-foreground" : "text-gold"}`}>{job.status === "completed" ? <CheckCircle2 size={13} /> : job.status === "failed" || job.status === "cancelled" ? <XCircle size={13} /> : <Clock3 size={13} />}{labelFor(job.status)}</span><span className="flex items-center gap-1 text-[10px] text-muted-foreground"><Zap size={12} className="text-gold" />{job.credits}</span><span className="text-[10px] text-muted-foreground">{job.createdAt}</span></div>{job.status === "processing" && <div className="mt-3 flex items-center gap-3 pl-12"><div className="h-1.5 flex-1 rounded-full bg-muted"><div className="h-1.5 rounded-full bg-gold transition-all" style={{ width: `${job.progress}%` }} /></div><span className="tabular-nums text-[10px] text-gold">{job.progress}%</span><button onClick={() => cancelJob(job.id)} className="rounded-md p-1 text-muted-foreground hover:bg-surface-hover hover:text-foreground" aria-label="Cancel job"><Trash2 size={13} /></button></div>}{job.status === "queued" && <div className="mt-3 flex items-center gap-2 pl-12 text-[10px] text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-gold" /> Waiting for an approved provider slot <button onClick={() => cancelJob(job.id)} className="ml-auto text-muted-foreground hover:text-foreground">Cancel</button></div>}</div>)}{filtered.length === 0 && <div className="px-5 py-12 text-center text-xs text-muted-foreground">No jobs match this filter.</div>}</div></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-border bg-card p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Queued</p><p className="mt-2 text-2xl font-semibold text-foreground">{jobs.filter((job) => job.status === "queued").length}</p><p className="mt-1 text-[10px] text-muted-foreground">Waiting for submission</p></div><div className="rounded-xl border border-border bg-card p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">In progress</p><p className="mt-2 text-2xl font-semibold text-foreground">{jobs.filter((job) => job.status === "processing").length}</p><p className="mt-1 text-[10px] text-gold">Credits reserved server-side</p></div><div className="rounded-xl border border-border bg-card p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Completed</p><p className="mt-2 text-2xl font-semibold text-foreground">{jobs.filter((job) => job.status === "completed").length}</p><p className="mt-1 text-[10px] text-emerald-300">Ready to review</p></div></div>
  </div></div>;
}
