"use client";

import { FormEvent, useState } from "react";
import { ArrowRight, Check, ExternalLink, Image as ImageIcon, Link2, Mic2, Play, Sparkles, Upload, Video, WandSparkles } from "lucide-react";
import { enqueueJob } from "@/lib/foundation";

const formats = ["UGC testimonial", "Product unboxing", "Tutorial", "TV commercial"];
const ratios = ["9:16", "1:1", "16:9"];

export default function MarketingStudioPage() {
  const [source, setSource] = useState("url");
  const [url, setUrl] = useState("https://cineforge.ai/product");
  const [format, setFormat] = useState(formats[0]);
  const [ratio, setRatio] = useState(ratios[0]);
  const [voice, setVoice] = useState("Warm founder");
  const [variants, setVariants] = useState(3);
  const [notice, setNotice] = useState("");

  const createCampaign = (event: FormEvent) => { event.preventDefault(); enqueueJob({ type: "ad", label: `${format} · ${variants} variants`, model: "Marketing Director", credits: variants * 16 }); setNotice(`Campaign queued · ${variants} ${format.toLowerCase()} variants`); };

  return <div className="h-full overflow-y-auto bg-background"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-gold"><Sparkles size={14} /> Marketing Studio</p><h1 className="mt-2 font-heading text-3xl font-semibold text-foreground">From product to campaign.</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">Drop in a product URL or image. CineForge will turn your brief into social-ready ad variants with voice, pacing, and visuals.</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-400/15 bg-emerald-400/10 px-3 py-2 text-[10px] text-emerald-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" /> Brand kit connected</div></div>{notice && <div className="mt-6 flex items-center gap-2 rounded-lg border border-gold/20 bg-gold/10 px-3 py-2.5 text-xs text-gold"><Check size={14} />{notice}</div>}

    <div className="mt-8 grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><form onSubmit={createCampaign} className="rounded-xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-foreground">Campaign brief</h2><p className="mt-1 text-xs text-muted-foreground">One source in. Many creative directions out.</p></div><WandSparkles size={17} className="text-gold" /></div><div className="mt-5 flex gap-2 rounded-lg border border-border bg-background p-1"><button type="button" onClick={() => setSource("url")} className={`flex flex-1 items-center justify-center gap-2 rounded-md py-2.5 text-xs ${source === "url" ? "bg-gold text-black" : "text-muted-foreground hover:text-foreground"}`}><Link2 size={14} /> Product URL</button><button type="button" onClick={() => setSource("image")} className={`flex flex-1 items-center justify-center gap-2 rounded-md py-2.5 text-xs ${source === "image" ? "bg-gold text-black" : "text-muted-foreground hover:text-foreground"}`}><ImageIcon size={14} /> Product image</button></div>{source === "url" ? <label className="mt-5 block"><span className="mb-1.5 block text-xs font-medium text-foreground/75">Product page URL</span><div className="flex items-center gap-2 rounded-md border border-input bg-background px-3"><Link2 size={14} className="text-muted-foreground" /><input required value={url} onChange={(event) => setUrl(event.target.value)} className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none" /></div><p className="mt-2 flex items-center gap-1.5 text-[10px] text-muted-foreground"><ExternalLink size={11} /> We’ll use visible product details and your connected brand kit.</p></label> : <label className="mt-5 flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-border bg-background/50 px-5 py-12 text-center hover:border-gold/50"><Upload size={22} className="text-gold" /><span className="mt-3 text-xs font-medium text-foreground">Upload a product image</span><span className="mt-1 text-[10px] text-muted-foreground">PNG, JPG, or WEBP · up to 20 MB</span><input type="file" accept="image/*" className="sr-only" /></label>}

      <div className="mt-6"><label className="text-xs font-medium text-foreground/75">Choose a format</label><div className="mt-2 grid grid-cols-2 gap-2">{formats.map((item) => <button type="button" key={item} onClick={() => setFormat(item)} className={`rounded-lg border px-3 py-3 text-left text-xs transition ${format === item ? "border-gold/50 bg-gold/10 text-gold" : "border-border text-muted-foreground hover:border-gold/25 hover:text-foreground"}`}><Video size={14} className="mb-2" />{item}</button>)}</div></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="block"><span className="mb-1.5 block text-xs font-medium text-foreground/75">Voice direction</span><div className="flex items-center gap-2 rounded-md border border-input bg-background px-3"><Mic2 size={14} className="text-muted-foreground" /><select value={voice} onChange={(event) => setVoice(event.target.value)} className="w-full bg-transparent py-3 text-sm outline-none"><option>Warm founder</option><option>Energetic creator</option><option>Calm expert</option><option>No voiceover</option></select></div></label><label className="block"><span className="mb-1.5 block text-xs font-medium text-foreground/75">Output ratio</span><div className="flex gap-1.5">{ratios.map((item) => <button type="button" key={item} onClick={() => setRatio(item)} className={`flex-1 rounded-md border py-3 text-xs ${ratio === item ? "border-gold/50 bg-gold/10 text-gold" : "border-input text-muted-foreground"}`}>{item}</button>)}</div></label></div>
      <div className="mt-6"><div className="flex items-center justify-between"><label className="text-xs font-medium text-foreground/75">Number of variants</label><span className="text-xs text-gold">{variants}</span></div><input type="range" min="1" max="6" value={variants} onChange={(event) => setVariants(Number(event.target.value))} className="mt-3 w-full accent-[#B9F33D]" /></div><button type="submit" className="mt-7 flex w-full items-center justify-center gap-2 rounded-md bg-gold py-3 text-xs font-semibold text-black hover:bg-gold-hover"><Sparkles size={14} /> Generate {variants} ad variants <ArrowRight size={14} /></button></form>

      <div className="space-y-4"><div className="relative overflow-hidden rounded-xl border border-border bg-[#0b1510] p-5"><div className="absolute -right-8 -top-8 h-40 w-40 rounded-full bg-gold/10 blur-3xl" /><div className="relative flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[0.16em] text-gold">Campaign preview</p><h2 className="mt-1 font-heading text-2xl text-white">Nocturne</h2><p className="mt-1 text-[10px] text-white/40">{format} · {ratio} · {voice}</p></div><button className="flex h-10 w-10 items-center justify-center rounded-full border border-white/20 bg-white/10 text-white hover:bg-gold hover:text-black" aria-label="Play preview"><Play size={15} fill="currentColor" /></button></div><div className="mt-6 aspect-[9/11] overflow-hidden rounded-lg border border-white/10 bg-gradient-to-br from-green-200/30 via-emerald-950/75 to-black"><div className="absolute" /><div className="flex h-full flex-col justify-between p-5"><span className="w-fit rounded-full bg-black/30 px-2 py-1 text-[8px] uppercase tracking-[0.15em] text-white/65">Product story · 01</span><div><div className="mb-3 h-px w-8 bg-gold" /><p className="max-w-[190px] font-heading text-xl leading-tight text-white">Your next favorite ritual.</p><p className="mt-2 max-w-[200px] text-[10px] leading-relaxed text-white/55">A quiet, considered moment for every day.</p><span className="mt-4 inline-flex rounded-full bg-gold px-3 py-1.5 text-[9px] font-semibold text-black">Shop now</span></div></div></div><div className="mt-4 flex items-center justify-between text-[10px] text-white/40"><span>Brand kit · Nocturne</span><span className="flex items-center gap-1"><Check size={11} className="text-emerald-300" /> Auto-captioned</span></div></div><div className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-foreground">Recent campaigns</h2><p className="mt-1 text-[10px] text-muted-foreground">Your latest marketing generations.</p></div><button className="text-[10px] text-gold">View all</button></div><div className="mt-4 space-y-3">{["Nocturne · launch week", "Verdant / UGC test", "Studio desk · retargeting"].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-lg border border-border p-3"><div className={`flex h-9 w-9 items-center justify-center rounded-md ${index === 0 ? "bg-gold/15 text-gold" : index === 1 ? "bg-violet-400/15 text-violet-300" : "bg-cyan-400/15 text-cyan-300"}`}><Video size={15} /></div><div className="min-w-0 flex-1"><p className="truncate text-xs text-foreground/80">{item}</p><p className="mt-1 text-[9px] text-muted-foreground">{index + 2} variants · {index === 0 ? "12 min ago" : "Yesterday"}</p></div><ArrowRight size={13} className="text-muted-foreground" /></div>)}</div></div></div></div>

    <div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-border bg-card p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Average production</p><p className="mt-2 text-2xl font-semibold text-foreground">4.2 min</p><p className="mt-1 text-[10px] text-emerald-300">from brief to first draft</p></div><div className="rounded-xl border border-border bg-card p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Best performing hook</p><p className="mt-2 text-sm font-semibold text-foreground">“Your next favorite ritual.”</p><p className="mt-1 text-[10px] text-muted-foreground">38% higher hold rate</p></div><div className="rounded-xl border border-border bg-card p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Exports this month</p><p className="mt-2 text-2xl font-semibold text-foreground">42</p><p className="mt-1 text-[10px] text-muted-foreground">Across 6 active campaigns</p></div></div>
  </div></div>;
}
