"use client";

import { ChangeEvent, useState } from "react";
import { ArrowUpRight, FileImage, Info, LockKeyhole, Plus, Sparkles, Trash2, Upload, UserRound, X } from "lucide-react";
import { CharacterIdentity, enqueueJob, getCharacters, saveCharacters } from "@/lib/foundation";

const statusLabels = { ready: "Ready to use", training: "Training identity", needs_consent: "Consent required" } as const;

export default function SoulIdPage() {
  const [characters, setCharacters] = useState<CharacterIdentity[]>(() => getCharacters());
  const [showCreate, setShowCreate] = useState(false);
  const [name, setName] = useState("");
  const [files, setFiles] = useState(0);
  const [consent, setConsent] = useState(false);
  const [notice, setNotice] = useState("");

  const chooseFiles = (event: ChangeEvent<HTMLInputElement>) => setFiles(event.target.files?.length ?? 0);
  const createIdentity = () => {
    if (!name.trim() || !consent || files < 3) { setNotice("Add at least 3 references and confirm documented consent before training."); return; }
    const character: CharacterIdentity = { id: `character-${Date.now()}`, name: name.trim(), status: "training", references: files, consistency: 18, updatedAt: "Just now" };
    const next = [character, ...characters]; setCharacters(next); saveCharacters(next); enqueueJob({ type: "character", label: `${character.name} identity training`, model: "Soul ID", credits: 120 }); setShowCreate(false); setName(""); setFiles(0); setConsent(false); setNotice(`${character.name} is queued for identity training.`);
  };

  return <div className="h-full overflow-y-auto bg-background"><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-gold"><Sparkles size={14} /> Soul ID</p><h1 className="mt-2 font-heading text-3xl font-semibold text-foreground">Characters that stay consistent.</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">Train an identity once, then carry the same face, wardrobe, and presence across every scene and model.</p></div><button onClick={() => setShowCreate(true)} className="inline-flex items-center gap-2 rounded-md bg-gold px-3.5 py-2.5 text-xs font-semibold text-black hover:bg-gold-hover"><Plus size={14} /> New identity</button></div>{notice && <div className="mt-6 flex items-center justify-between rounded-lg border border-gold/20 bg-gold/10 px-3 py-2.5 text-xs text-gold"><span className="flex items-center gap-2"><Info size={14} />{notice}</span><button onClick={() => setNotice("")} aria-label="Dismiss"><X size={14} /></button></div>}

    {showCreate && <section className="mt-7 rounded-xl border border-gold/25 bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-heading text-xl text-foreground">Create a Soul ID</h2><p className="mt-1 text-xs text-muted-foreground">Reference media is private to your workspace and never shown as a public asset.</p></div><button onClick={() => setShowCreate(false)} className="rounded-md p-1.5 text-muted-foreground hover:bg-surface-hover" aria-label="Close"><X size={15} /></button></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1fr]"><div><label className="block"><span className="mb-1.5 block text-xs font-medium text-foreground/75">Identity name</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Mara Chen" className="w-full rounded-md border border-input bg-background px-3 py-3 text-sm outline-none focus:border-gold" /></label><label className="mt-4 flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-border bg-background/50 px-5 py-10 text-center hover:border-gold/50"><Upload size={22} className="text-gold" /><span className="mt-3 text-xs font-medium text-foreground">Upload reference photos</span><span className="mt-1 text-[10px] text-muted-foreground">Use 12–24 clear images, multiple angles, and consistent lighting.</span><input type="file" multiple accept="image/*" onChange={chooseFiles} className="sr-only" />{files > 0 && <span className="mt-3 rounded-full bg-gold/10 px-2.5 py-1 text-[10px] text-gold">{files} files selected</span>}</label></div><div className="rounded-xl border border-border bg-background/50 p-4"><div className="flex items-start gap-3"><LockKeyhole size={16} className="mt-0.5 text-emerald-300" /><div><p className="text-xs font-medium text-foreground">Consent and provenance</p><p className="mt-1 text-[10px] leading-relaxed text-muted-foreground">Only upload people you are authorized to represent. Keep a record of consent and the source of each reference set.</p></div></div><label className="mt-6 flex gap-2.5 text-xs text-foreground/70"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-0.5 accent-[#B9F33D]" />I confirm I have documented consent to create this identity.</label><div className="mt-6 grid grid-cols-2 gap-2 text-[10px] text-muted-foreground"><div className="rounded-lg border border-border p-3"><p className="text-foreground/75">Minimum</p><p className="mt-1 text-gold">3 references</p></div><div className="rounded-lg border border-border p-3"><p className="text-foreground/75">Recommended</p><p className="mt-1 text-gold">12–24 photos</p></div></div><button onClick={createIdentity} className="mt-6 flex w-full items-center justify-center gap-2 rounded-md bg-gold py-3 text-xs font-semibold text-black hover:bg-gold-hover"><Sparkles size={14} /> Train identity · 120 credits</button></div></div></section>}

    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{characters.map((character) => <article key={character.id} className="group overflow-hidden rounded-xl border border-border bg-card"><div className="relative flex h-44 items-center justify-center overflow-hidden bg-gradient-to-br from-emerald-900/50 via-background to-violet-950/40"><div className="absolute -left-10 top-4 h-32 w-32 rounded-full bg-gold/10 blur-3xl" /><div className="relative flex h-24 w-24 items-center justify-center rounded-full border border-white/15 bg-gradient-to-br from-gold/40 to-emerald-950 text-3xl font-heading text-foreground shadow-2xl"><UserRound size={36} /></div><span className="absolute left-3 top-3 rounded-full border border-white/10 bg-black/20 px-2 py-1 text-[9px] text-white/60 backdrop-blur">{character.references} refs</span></div><div className="p-4"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-foreground">{character.name}</h2><p className="mt-1 text-[10px] text-muted-foreground">Updated {character.updatedAt}</p></div><span className={`rounded-full px-2 py-1 text-[9px] ${character.status === "ready" ? "bg-emerald-400/10 text-emerald-300" : "bg-gold/10 text-gold"}`}>{statusLabels[character.status]}</span></div><div className="mt-4 flex items-center justify-between text-[10px] text-muted-foreground"><span>Consistency score</span><span className="text-foreground/75">{character.consistency}%</span></div><div className="mt-2 h-1 rounded-full bg-muted"><div className="h-1 rounded-full bg-gold" style={{ width: `${character.consistency}%` }} /></div><div className="mt-4 flex items-center justify-between"><button className="text-[10px] text-muted-foreground hover:text-foreground">View references <ArrowUpRight className="ml-1 inline" size={12} /></button><button className="rounded-md p-1.5 text-muted-foreground hover:bg-surface-hover hover:text-foreground" aria-label={`Delete ${character.name}`}><Trash2 size={14} /></button></div></div></article>)}<button onClick={() => setShowCreate(true)} className="flex min-h-[310px] flex-col items-center justify-center rounded-xl border border-dashed border-border bg-card/40 text-muted-foreground transition hover:border-gold/40 hover:bg-card hover:text-gold"><Plus size={20} /><span className="mt-3 text-xs font-medium">Create new identity</span><span className="mt-1 text-[10px]">Train once · reuse everywhere</span></button></div>

    <div className="mt-8 rounded-xl border border-border bg-card p-5"><div className="flex items-start gap-3"><FileImage size={17} className="mt-0.5 text-gold" /><div><h2 className="text-sm font-semibold text-foreground">How Soul ID works</h2><p className="mt-1 max-w-2xl text-xs leading-relaxed text-muted-foreground">Your identity becomes a governed workspace asset. Every generation job can reference it, while consent status, source notes, and retention are kept alongside the character record.</p></div></div></div></div></div>;
}
